I'm sorry, but an uncaught exception occurred.

While parsing /Users/teajakic/Developer/pokusaj/game/script.rpy.
ScriptError: Name u'start' is defined twice, at game/dse-3.1/game/main.rpy:36 and game/script.rpy:118.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/teajakic/Downloads/New Folder With Items/renpy-6.99.7-sdk/renpy/bootstrap.py", line 281, in bootstrap
    renpy.main.main()
  File "/Users/teajakic/Downloads/New Folder With Items/renpy-6.99.7-sdk/renpy/main.py", line 346, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "/Users/teajakic/Downloads/New Folder With Items/renpy-6.99.7-sdk/renpy/script.py", line 259, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "/Users/teajakic/Downloads/New Folder With Items/renpy-6.99.7-sdk/renpy/script.py", line 738, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "/Users/teajakic/Downloads/New Folder With Items/renpy-6.99.7-sdk/renpy/script.py", line 414, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name u'start' is defined twice, at game/dse-3.1/game/main.rpy:36 and game/script.rpy:118.

Darwin-14.3.0-x86_64-i386-64bit
Ren'Py 6.99.7.858
 
